### PR TITLE
Initial tag added

### PR DESCRIPTION
**Pull request by insaurabh**

### CODE REVIEW

**Comment by userbott** [comment]
Make a detailed video from the beginning of the installation of the plugin to create pages and customize the template. All stages of installation. Thank !

**Comment by anshul321** [comment]
Hi, Thanks for your comment.
Can you please post the same over the issues section?

As for the previous message, I would suggest that you can refer back to the [gif](https://github.com/Hestabit/craft-ajaxinate/blob/master/resources/img/craft-entry-loader-settingpage.gif) and if something is still not clear then please let me know.

Thanks and Regards

**Comment by userbott** [comment]
GIF - Too fast and not clear. What to put (


От 12 июля 2019 г. в 17:36:29, Anshul Mishra (notifications@github.com)
написал:

Hi, Thanks for your comment.
Can you please post the same over the issues section?

As for the previous message, I would suggest that you can refer back to the
gif
<https://github.com/Hestabit/craft-ajaxinate/blob/master/resources/img/craft-entry-loader-settingpage.gif>
and if something is still not clear then please let me know.

Thanks and Regards

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Hestabit/craft-ajaxinate/pull/1?email_source=notifications&email_token=ADXH4743WJW6E3CSFQLPJOLP7CJG3A5CNFSM4H7OYNR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZZ577Q#issuecomment-510910462>,
or mute the thread

**Comment by anshul321** [comment]
Hi again,
Let me create a step by step procedure of how to implement the plugin so that you can easily follow the steps. In the meantime, you can refer to the plugin's documentation. Hope [documentation](https://github.com/Hestabit/craft-ajaxinate#steps-to-add-load-more-functionality) will be able to sort the issue that you're facing..

Can you please post the issue over the issues section. Here is the URL: https://github.com/Hestabit/craft-ajaxinate/issues

Thanks

**Pull request merged**
